"""Load operator profiles from JSON and adapt for harness.

Instead of manual op_specs.py, we load auto-generated operator profiles
from op_profiles_complete.json. This JSON is generated by schema_gen.py
and contains complete dtype/attribute/constraint info extracted from ONNX schema.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# Standard shapes to test for all operators
DEFAULT_SHAPES = ("BCHW", "B-C-1-1", "B-1-H-1", "scalar")
DEFAULT_FILLS = ("random", "sparse", "alternating")
BOOL_FILLS = ("all_true", "all_false", "alternating")

MAX_CASES_PER_OP = 128
DEFAULT_OPSET = 11


@dataclass(frozen=True)
class InputPort:
    """Input port specification."""
    name: str
    is_init: bool = False
    is_optional: bool = False
    type_param: str = ""
    shape_labels: tuple[str, ...] = DEFAULT_SHAPES
    dtype_labels: tuple[str, ...] = ("float32", "float16", "int32", "int64", "bool", "uint8")
    fill_labels: tuple[str, ...] = DEFAULT_FILLS
    tied_dtype_to: str | None = None


@dataclass(frozen=True)
class OutputPort:
    """Output port specification."""
    name: str
    type_param: str = ""
    is_optional: bool = False
    dtype_labels: tuple[str, ...] = ()


@dataclass(frozen=True)
class AttrSpec:
    """Small slice of ONNX attribute schema used by the generator."""
    attr_type: str
    required: bool = False
    default: object = None


@dataclass(frozen=True)
class OpSpec:
    """Operator specification."""
    name: str
    inputs: tuple[InputPort, ...] = ()
    attrs: dict[str, tuple] = None
    attr_specs: dict[str, AttrSpec] = None
    outputs: tuple[OutputPort, ...] = ()
    opset: int = 11
    output_count: int = 1
    notes: str = ""
    pinned_fills: dict[str, str] = None
    pinned_values: dict[str, object] = None
    static_inits: tuple[tuple[str, str, str, object], ...] = ()

    def __post_init__(self):
        if self.attrs is None:
            object.__setattr__(self, 'attrs', {})
        if self.attr_specs is None:
            object.__setattr__(self, 'attr_specs', {})
        if self.pinned_fills is None:
            object.__setattr__(self, 'pinned_fills', {})
        if self.pinned_values is None:
            object.__setattr__(self, 'pinned_values', {})
        if not self.outputs and self.output_count:
            object.__setattr__(self, 'outputs', tuple(
                OutputPort(name=f"output_{i}") for i in range(self.output_count)
            ))


def _onnx_dtype_to_test_dtype(onnx_dtype: str) -> str | None:
    """Map ONNX dtype name to test dtype name."""
    mapping = {
        "float": "float32",
        "double": "float64",
        "float16": "float16",
        "int8": "int8",
        "int16": "int16",
        "int32": "int32",
        "int64": "int64",
        "uint8": "uint8",
        "uint16": "uint16",
        "uint32": "uint32",
        "uint64": "uint64",
        "bool": "bool",
    }
    return mapping.get(onnx_dtype)


def _extract_tensor_dtype(type_str: str) -> str | None:
    """Return our dtype label for concrete ONNX type strings like tensor(int64)."""
    if type_str.startswith("tensor(") and type_str.endswith(")"):
        return _onnx_dtype_to_test_dtype(type_str[len("tensor("):-1])
    return None


def _dtype_labels_for(type_param: str, profile: dict[str, Any]) -> tuple[str, ...]:
    dtype_labels = set()
    if type_param in profile.get("type_constraints", {}):
        for onnx_dt in profile["type_constraints"][type_param]:
            if test_dt := _onnx_dtype_to_test_dtype(onnx_dt):
                dtype_labels.add(test_dt)
    elif concrete := _extract_tensor_dtype(type_param):
        dtype_labels.add(concrete)
    return tuple(sorted(dtype_labels))


def _shape_labels_for(type_param: str) -> tuple[str, ...]:
    # Control inputs such as TopK.K, Split.split, Slice.starts are usually
    # small vectors/scalars, not BCHW-like tensors.
    return ("1d-1", "1d-10") if _extract_tensor_dtype(type_param) in {"int32", "int64"} else DEFAULT_SHAPES


def _profile_to_opspec(profile: dict[str, Any]) -> OpSpec:
    """Convert a JSON profile to an OpSpec for harness compatibility."""
    op_name = profile["name"]
    opset = profile["opset"]

    # Extract input ports from profile
    inputs = []
    required_inputs = []
    optional_inputs = []

    for inp in profile["inputs"]:
        name = inp["name"]
        is_optional = inp["is_optional"]
        type_param = inp["type_param"]

        dtype_labels = _dtype_labels_for(type_param, profile)
        if not dtype_labels:
            # Non-tensor/sequence/map inputs are not useful to this simple
            # tensor-only generator yet.
            continue

        # Use bool-specific fills if dtype is only bool
        fill_labels = BOOL_FILLS if dtype_labels == ("bool",) else DEFAULT_FILLS

        # Optional/control inputs are easiest to include as initializers.
        is_init = is_optional or _extract_tensor_dtype(type_param) in {"int32", "int64", "float32", "bool"}

        # Find tied_dtype_to from profile
        tied_to = profile.get("tied_dtypes", {}).get(name)

        port = InputPort(
            name=name,
            is_init=is_init,
            is_optional=is_optional,
            type_param=type_param,
            shape_labels=_shape_labels_for(type_param),
            dtype_labels=dtype_labels,
            fill_labels=fill_labels,
            tied_dtype_to=tied_to,
        )
        inputs.append(port)

        if is_optional:
            optional_inputs.append(name)
        else:
            required_inputs.append(name)

    # Extract attributes
    attrs = {}
    attr_specs = {}
    for attr_name, attr_spec in profile.get("attributes", {}).items():
        attrs[attr_name] = ()
        attr_specs[attr_name] = AttrSpec(
            attr_type=attr_spec.get("type", ""),
            required=bool(attr_spec.get("required", False)),
            default=attr_spec.get("default"),
        )

    # Determine output count
    outputs = []
    for out in profile.get("outputs", []):
        type_param = out["type_param"]
        outputs.append(OutputPort(
            name=out["name"],
            type_param=type_param,
            is_optional=out.get("is_optional", False),
            dtype_labels=_dtype_labels_for(type_param, profile),
        ))
    output_count = len(outputs) or 1

    notes = f"Auto-generated from ONNX schema (opset {opset})"
    if optional_inputs:
        notes += f". Optional inputs: {', '.join(optional_inputs)}"

    return OpSpec(
        name=op_name,
        inputs=tuple(inputs),
        attrs=attrs,
        attr_specs=attr_specs,
        outputs=tuple(outputs),
        opset=opset,
        output_count=output_count,
        notes=notes,
    )


def load_profiles(profile_file: str | Path = "op_profiles_complete.json",
                  *, opset: int | None = DEFAULT_OPSET) -> dict[str, OpSpec]:
    """Load operator profiles from JSON and convert to OpSpec format.

    Returns a dict mapping op_name -> OpSpec for one opset.
    """
    profile_path = Path(profile_file)

    # If relative path, resolve relative to this module's directory
    if not profile_path.is_absolute():
        module_dir = Path(__file__).resolve().parent
        profile_path = module_dir / profile_file

    if not profile_path.exists():
        # Fallback: return empty dict or try to load from default location
        print(f"Warning: profile file {profile_path} not found. Using empty SPECS.")
        return {}

    with open(profile_path) as f:
        profiles_json = json.load(f)

    specs = {}
    for profile_key, profile_data in profiles_json.items():
        if opset is not None and int(profile_data["opset"]) != int(opset):
            continue
        # profile_key is like "Add_opset11"
        op_name = profile_data["name"]
        try:
            specs[op_name] = _profile_to_opspec(profile_data)
        except Exception as e:
            print(f"Warning: Failed to convert profile for {op_name}: {e}")

    return specs


# Load profiles at module import time from auto-generated JSON
SPECS = load_profiles()


def list_specs(only: list[str] | None = None, *, opset: int | None = DEFAULT_OPSET) -> list[OpSpec]:
    """List available operator specs, optionally filtered."""
    source = SPECS if opset == DEFAULT_OPSET else load_profiles(opset=opset)
    specs = []
    for op_name, spec in sorted(source.items()):
        if only and op_name not in only:
            continue
        specs.append(spec)
    return specs


def get_spec(name: str, *, opset: int | None = DEFAULT_OPSET) -> OpSpec:
    source = SPECS if opset == DEFAULT_OPSET else load_profiles(opset=opset)
    return source[name]


__all__ = [
    "OpSpec", "InputPort", "OutputPort", "AttrSpec",
    "SPECS", "DEFAULT_OPSET", "MAX_CASES_PER_OP",
    "load_profiles", "list_specs", "get_spec",
]
